project_id = "gmwdwxkfygppiavyysyv"

[functions.fetch-odds-api-scores]
verify_jwt = false

[functions.fetch-live-analytics]
verify_jwt = false

[functions.fetch-live-odds]
verify_jwt = false

[functions.get-prop-analytics]
verify_jwt = false

[functions.populate-prop-analytics]
verify_jwt = false

[functions.fetch-sports-schedule]
verify_jwt = false

[functions.fetch-livesport-scores]
verify_jwt = false

[functions.external-factors-ai]
verify_jwt = false

[functions.analyze-edge-opportunities]
verify_jwt = false

[functions.analyze-parlay-image]
verify_jwt = false

[functions.sports-insights-ai]
verify_jwt = false

[functions.populate-live-data]
verify_jwt = false

[functions.populate-matchups]
verify_jwt = false

[functions.fetch-thescore-data]
verify_jwt = false
