project_id = "gmwdwxkfygppiavyysyv"

[functions.fetch-live-analytics]
verify_jwt = false

[functions.fetch-live-odds]
verify_jwt = false

[functions.get-prop-analytics]
verify_jwt = false

[functions.fetch-sports-schedule]
verify_jwt = false

[functions.fetch-livesport-scores]
verify_jwt = false