// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmwdwxkfygppiavyysyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtd2R3eGtmeWdwcGlhdnl5c3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjkzMzgsImV4cCI6MjA3MzEwNTMzOH0.qQAI-KuN4xeZQ5GYyrFanyIUPZTiHZT7VrKdmHPN8gA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});